[2020-04-08 09:45:15] CKFinder.WARNING: ErrorException: Undefined variable: _SESSION in I:\NewServer\data\myls_framework\web\ckfinder\config.php:29 Stack trace: #0 I:\NewServer\data\myls_framework\web\ckfinder\config.php(29): CKSource\CKFinder\ExceptionHandler->errorHandler(8, 'Undefined varia...', 'I:\\NewServer\\da...', 29, Array) #1 [internal function]: CKSource\CKFinder\Config->{closure}() #2 I:\NewServer\data\myls_framework\web\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\Authentication\CallableAuthentication.php(45): call_user_func(Object(Closure)) #3 I:\NewServer\data\myls_framework\web\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(218): CKSource\CKFinder\Authentication\CallableAuthentication->authenticate() #4 I:\NewServer\data\myls_framework\web\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(539): CKSource\CKFinder\CKFinder->checkAuth() #5 I:\NewServer\data\myls_framework\web\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(600): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #6 I:\NewServer\data\myls_framework\web\ckfinder\core\connector\php\vendor\cksource\ckfinder\src\CKSource\CKFinder\CKFinder.php(346): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 I:\NewServer\data\myls_framework\web\ckfinder\core\connector\php\connector.php(20): CKSource\CKFinder\CKFinder->run() #8 {main} [] []
